### ISSUE TITLE
Minecraft 1.8 update

### ISSUE THREAD

**Issue by SpaceManiac** [GlowstoneMC/Glowstone-Legacy#131]
http://wiki.vg/Protocol

general todo:
- [x] get connection and operation working in the general case (yay!)
- [x] update pipeline for compression (without breaking encryption)
- [x] add configuration option for compression
- [ ] figure out deal with flow-networking usage (see #378)
- [x] get chunk sending working again
- [x] update chunk format internals for protocol format changes
- [ ] update BlockType internals for new state system (see #379)
- [x] update Bukkit for new Material entries and such
- [x] add the new crafting recipes (see #314)
- [ ] update `scoreboard` branch packets (see #81 and PRs #331 and #340)
- [x] get at least most of the remaining protocol stuff below done

play outbound todo:
- [x] update slot data type
- [x] change SpawnPlayerMessage to not contain whole profile
- [x] fix SpawnPlayerCodec to use UUID data type on wire
- [x] on ground flags in entity move messages
- [x] chunk data and chunk bulk
- [x] multi block change
- [x] block change message type id stuff
- [x] window type strings
- [x] sign json conversion
- [x] map data packet
- [x] tab list entry
- [x] support for property updates in UserListItemCodec
- [x] fixes to PlayParticleCodec (need to determine format details) (see `particles` branch)

play outbound new packets (need codecs):
- [x] 0x41 server difficulty
- [x] 0x42 combat event
- [x] 0x43 camera
- [x] 0x44 world border
- [x] 0x45 title
- [x] 0x46 set compression
- [x] 0x47 player list header/footer
- [x] 0x48 resource pack send
- [x] 0x49 entity update nbt

play inbound todo:
- [x] sign json conversion
- [x] fix player arm swing stuff
- [x] steer vehicle flag cleanup

play inbound new packets (need codecs and stub handlers):
- [x] 0x18 spectate
- [x] 0x19 resource pack status

login outbound new packets (need codecs):
- [x] 0x3 set compression

**Comment by Leymooo** [comment]
update play outbound new packets
