### ISSUE TITLE
List of 'issues' as i find them

### ISSUE THREAD

**Issue by KakusiUgbe** [GlowstoneMC/Glowstone-Legacy#292]
Hi!

First i would like to thank you for making Glowstone and working on it to be brought to 1.8. I really appreciate it.

Now to the point of theis 'issue' report.

1, So far non of the doors placed display in game properly. They only show the top half and they can't be operated. When right clicked they simply vanish. (This includes all wooden doors and iron door)

2, Block placing makes the same sound that is kinda wooden sound no matter the block we place.

3, Redsandstone stairs always snap to East with the taller side. Unable to place them upside down.

4, Redsandstone slabs snap to lower position even when placed on ceiling.

5, Placed Crafting table opens a 9 slot chest like inventory named Crafting.

6, 2 chest placed side by side do conjoin into a double chest, but remains 2 separate 27 slot inventory. 

7, Placed furnace does show proper GUI, but accepts any item/block for fuel, and smelting process doesn't start.

8, Breaking bottom block of Cactus doesn't break entire plant.

9, Jukebox doesn't take disks

10, Enchantment table behaves like solid block. Other blocks are placed on it instead of opening GUI.

11, End portal frame doesn't accept Eye of Ender.

12, All chests lack opening and closing animation. (Including Enderchest that otherwise works like a charm)

13, Anvils snap to face east-west except for slightly damaged one that snaps to north-south. Also no GUI and block can be just placed on them.

14, Acacia and DarkOak leaves look like Oak leaves when placed.

15, Paintings cannot be placed.

16, Itemframes cannot be placed.

17, Flower placed in a flowerpot will be placed inside and one next to/above the flower pot unless the block next to or above is blocked. (can be blocked by player.

18, Placing various heads doesn't change the texture, but the position of it. The collision box will be where i place it, but visually it's facing elsewhere or floats in the air.

19, Armor stand and banner can't be placed. Probably not done yet. :)

20, Noteblock can be placed, on rightclick it shows the 'notes' coming from it, but no sound.

21, Ofc, Redstone stuff and rail stuff doesn't work, but i'm sure it's being worked on.

22, Beacon GUI is not there yet.

Note: I was positively surprised by the Beacon beam working and getting colored by stained glass :) 

Once again, thank you guys for working on it, i wish i was any good at coding so i could help. If there is any way i can help make this project happen without any coding knowledge do let me know!

**Comment by Wild1145** [comment]
Can I suggest splitting these up into multiple issues? That way the developers can be working on one issue at a time instead of trying to keep up with your 22 long list :)

**Comment by Wild1145** [comment]
Doors are already a known issue in #290 just so you know, and they have said someone is working on it :)

**Comment by Wild1145** [comment]
I think your number 3 ( 3, Redsandstone stairs always snap to East with the taller side. Unable to place them upside down. ) Is already known of and being worked on in #285

**Comment by Wild1145** [comment]
6, 2 chest placed side by side do conjoin into a double chest, but remains 2 separate 27 slot inventory. Is already a known issue in #263

**Comment by daboross** [comment]
Wood sound issue here: https://github.com/GlowstoneMC/Glowstone/issues/99

**Comment by dequis** [comment]
Can we turn this into a checklist and check items as they get their own issue?

**Comment by dequis** [comment]
Bah whatever, doing it in a comment
- [x] 1, So far non of the doors placed display in game properly. They only show the top half and they can't be operated. When right clicked they simply vanish. (This includes all wooden doors and iron door) - #290 
- [x] 2, Block placing makes the same sound that is kinda wooden sound no matter the block we place. - #99 
- [x] 3, Redsandstone stairs always snap to East with the taller side. Unable to place them upside down. - #285 
- [x] 4, Redsandstone slabs snap to lower position even when placed on ceiling.
- [x] 5, Placed Crafting table opens a 9 slot chest like inventory named Crafting - #202
- [x] 6, 2 chest placed side by side do conjoin into a double chest, but remains 2 separate 27 slot inventory. - #263 
- [x] 7, Placed furnace does show proper GUI, but accepts any item/block for fuel, and smelting process doesn't start - #1 
- [x] 8, Breaking bottom block of Cactus doesn't break entire plant.
- [x] 9, Jukebox doesn't take disks
- [x] 10, Enchantment table behaves like solid block. Other blocks are placed on it instead of opening GUI.
- [x] 11, End portal frame doesn't accept Eye of Ender.
- [x] 12, All chests lack opening and closing animation. (Including Enderchest that otherwise works like a charm) - PR #211 
- [x] 13, Anvils snap to face east-west except for slightly damaged one that snaps to north-south. Also no GUI and block can be just placed on them.
- [x] 14, Acacia and DarkOak leaves look like Oak leaves when placed.
- [x] 15, Paintings cannot be placed - #139 
- [x] 16, Itemframes cannot be placed - #139 - PR #280 
- [x] 17, Flower placed in a flowerpot will be placed inside and one next to/above the flower pot unless the block next to or above is blocked. (can be blocked by player.
- [x] 18, Placing various heads doesn't change the texture, but the position of it. The collision box will be where i place it, but visually it's facing elsewhere or floats in the air.
- [x] 19, Armor stand and banner can't be placed. Probably not done yet. :)
- [x] 20, Noteblock can be placed, on rightclick it shows the 'notes' coming from it, but no sound.
- [x] 21, Ofc, Redstone stuff and rail stuff doesn't work, but i'm sure it's being worked on - #116
- [x] 22, Beacon GUI is not there yet.

**Comment by daboross** [comment]
It might be helpful to make these separate issues though, so that they can be tracked and closed separate, as well as associated with PRs.

**Comment by dequis** [comment]
Yeah the checklist is for that - to track which ones have those separate issues already.

**Comment by dequis** [comment]
Item 12 (chest sounds/animations) is being worked at #211 but doesn't have a corresponding issue

Item 15 (paintings), issue #139 

Item 16 (item frames) is being worked at #280, issue #139 

Item 21 (redstone), issue #116

Item 5 (workbench inventory), issue #202

Item 7 (smelting), issue #1

**Comment by Wild1145** [comment]
See now #297 #298 #299 #300 #301 #302 #303 #304 #305 #306 #307 #308 for the breakdown of this issue.

**Comment by KakusiUgbe** [comment]
Thank you! And thank you for the Checklist. I have made new Issues for the ones on the checklist that wasn't checked, and it turns out some have had and issue already :) 

I hope my posts help the project. :) I think this can be closed now.
