### ISSUE TITLE
Bad drop mappings

### ISSUE THREAD

**Issue by turt2live** [GlowstoneMC/Glowstone-Legacy#527]
This is an extension of #98 so that it doesn't get cluttered.

Known/confirmed cases. Checked means 'resolved in master'.
- _Coming Soon_

_Update: List is being generated [here](https://docs.google.com/spreadsheets/d/1Qgky1a2zsUeKfOblpNLmmVF95QmkKd_bh0tvuu143tA/edit#gid=0)_

**Comment by dequis** [comment]
WIP comment (delete and move to subject when it's done) for the broken items I've found so far (all drop as textureless purple/black items)
- [ ] Wooden slabs
- [ ] Rails
- [ ] Redstone
- [ ] Redstone torches [test and add other redstone stuff here]
- [ ] Trapped chest
- [ ] Lit furnace (as found in [exmaple](https://github.com/overviewer/Minecraft-Overviewer-Addons/tree/master/exmaple), [zip](http://i.turt2live.com/MoWQ.zip)) - it's a different item id, but should drop furnace instead
- [ ] Block of quartz
- [ ] Hay bale
- [ ] Ladders
- [ ] Wood/Iron trapdoors (fixed in #467)
- [ ] Fence gates (all variants)
- [ ] Pumpkins
- [ ] Jack-o-lanterns
- [ ] Red sandstone stairs (fixed in #467)
- [ ] Horizontal logs

Wrong drops, but appear like a correct item in client:
- [ ] Sea lanterns (should be prismarine)
- [ ] Stained glass panes
- [ ] Stained glass blocks
- [ ] Stained clay (fixed in #467)
- [ ] Coarse dirt
- [ ] Granite (and variants, incl. polished) (fixed in #467)

**Comment by turt2live** [comment]
Closing this to clean up my issues list on Github. If this is still an issue, please port it over to https://github.com/GlowstoneMC/Glowstone
